version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    target-branch: main
    ignore:
      # only upgrade by minor or patch
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
